### ISSUE TITLE
Problem with isAuthorized

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-security-passportjs#1]
Using Google there seems to be a mismatch between the user details stored in the cookie and that stored on the server

**Comment by paul90** [comment]
Reopening: That will not work with any legacy Persona :(

**Comment by WardCunningham** [comment]
Can you say a few words about the problem's root cause?

**Comment by paul90** [comment]
The root cause is that I when I added the legacy Persona login I intended to change the other integrations to store the user's identity in the cookie in the same format as used in `owner.json`.

I got distracted, and forgot that I hadn't made that change. This is a relatively simple change to make, just need to find the time to dedicate to doing it without distractions.
