### ISSUE TITLE
Modularising strategies

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-security-passportjs#13]
As a wiki farm host, I would like to provide custom strategies to my environments, i.e. GitLab.
Does it appear suitable to increase the level of modularity even more and refactor (potential) strategies into separate files or even npm modules?

**Comment by almereyda** [comment]
This could help increasing the number of available identity providers which don't restrict the callback URI. #10

**Comment by paul90** [comment]
> I would like to provide custom strategies to my environments

There is nothing stopping you, from extending this security plugin (cloning your own version and/or contributing pull request) or writing your own security plugin to support the custom strategies you require.
