### ISSUE TITLE
Support passport-local

### ISSUE THREAD

**Issue by bashrc** [fedwiki/wiki-security-passportjs#16]
I don't want to be dependent upon proprietary identity providers, so there should be an independent identity system if the federated wiki is to be viable.

**Comment by WardCunningham** [comment]
You must be looking for https://github.com/fedwiki/wiki-security-friends

**Comment by bashrc** [comment]
It's not really clear how this is supposed to work. Is there supposed to be some kind of login? Where is owner.json?

**Comment by WardCunningham** [comment]
We have resisted implementing a full-featured password recovery and anti-abuse identity system and have instead delegated that to proprietary providers as you note. This alone has not been fun as we chose Mozilla Passport for their good politics but that service closed as did the OpenID providers we chose before them.

I did not realize when I first responded that "passport-local" was a thing. I now understand that if we had an identity system we might offer passport-local as a login mechanism to it. But I don't see where password recovery is provided by passport-local.

We offer "friends" as an alternative to passport for the case where a site owner and a server administrator are friends who are able to keep a shared secret among themselves. The secret is kept in the owner.json file. If a site owner forgets the secret then his friend, the server administrator, can look in the owner.json file and forward it by some suitably secure channel. This is particularly useful on a LAN that does not have access to the internet.

Maybe you could say a few more words about the problem you are hoping to solve and how you would expect wiki to participate in that solution.

**Comment by WardCunningham** [comment]
I've opened an issue at wiki-security-friends concerning the challenges of putting it to use.

https://github.com/fedwiki/wiki-security-friends/issues/8
