### ISSUE TITLE
Google callback URL incorrect

### ISSUE THREAD

**Issue by kevinrutherford** [fedwiki/wiki-security-passportjs#24]
I'm running fedwiki on a server in Docker, using a forked version of federated-wiki/docker-wiki-core. I'm not running as a farm, because there will only ever be one wiki. I am trying to set up Google OAuth authentication, but the redirect URL passed to Google is always incorrect.

The redirect URL sent should be https://mywiki.example.com/auth/google/callback, but instead it is always sent as https://localhost:3000/auth/google/callback.

It seems that this security module isn't passed wiki_host in non-farm mode?

**Comment by WardCunningham** [comment]
Is wikiDomains what you are looking for?

https://github.com/fedwiki/wiki-security-passportjs/blob/master/docs/config-google.md#configure-wiki

**Comment by kevinrutherford** [comment]
I read that page as implying that wikiDomains only applies in the farm case; see also https://github.com/fedwiki/wiki/blob/4c6eee69e78c1ba3f3fc8d61f4450f70afb78f10/cli.coffee#L85. If I read it wrong, can you point me to something that describes how to use wikiDomains?

**Comment by WardCunningham** [comment]
You may be right. I have consulted my various installations and find that the only sites that are not farms use Friends security. This works because I am my own friend. You might cut through a lot of configuration hassle if you chose Friends too.

**Comment by paul90** [comment]
Looks as if without wikiDomain being set an unhelpful default for the `url` parameter is being used.

This can be resolved by setting the `url` parameter to `https://mywiki.example.com` should resolve the issue.

**Comment by paul90** [comment]
Setting `wikiDomains` when not using farm mode is not useful, as the code that sets the `url` is part of the farm code.

**Comment by WardCunningham** [comment]
Ah, yes. Here is the line:

https://github.com/fedwiki/wiki/blob/7e2e32b64974dac4a9bfe689dc9adbd7249fbfa3/farm.coffee#L129
