### ISSUE TITLE
`idProvider:  undefined`

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-security-passportjs#41]
When clicking Logout in any of the open tabs of any subdomain of wikis in a farm that use the same identity, nothing happens and the server throws `idProvider:  undefined`.

Reloading each page will display it as logged out.

This farm has GitHub and Google configured as providers.

How could I debug this any further? I there a debug toggle that I can set for the wiki server, so it maybe provides more details?

**Comment by almereyda** [comment]
The displayed logged out state will not be perfectly clean.

To reproduce:

1. Login to a farm site with Google
2. See all other tabs of wikis in the farm that use Google unlock
3. Logout in the first or one of the others
4. See `idProvider: undefined` in the server log.
5. Reload the tab(s) and login to GitHub (which should fail, because we only allow one owner (for now?))
6. See `idProvider: undefined` appear during login flow as well.
7. Finish login procedure and be logged in to Google again. Server logs `idProvider: google` again.

This reproduces in either order for Google and GitHub.

This happens basically when using multiple identities on multiple wikis in a farm with multiple identity providers enabled and breaks the security model.

I would have to reverse engineer the flows involved, to be able to tell where this breaks.

**Comment by paul90** [comment]
This problem is fixed in wiki-security-passportjs@0.9.0, which is included in wiki@0.33.0

**Comment by almereyda** [comment]
I've now tested this and unfortunately I am not able to complete the following steps:

1. Open **site 1**
2. Login to **site 1** with Google identity.
3. Open **site 2**, see the lock icon tilted.
4. Click the tilted lock icon to log out. Console switches from `idProvider: google` to `idProvider: undefined`
5. Login to **site 2** with GitHub identity. Console switches to `idProvider: google`.

---

After restarting the server and resetting the sessions, there is another thing that appears:

1. Open **site 2**
2. Login to **site 2** with GitHub identity
3. Open **site 1**
4. Login to **site 1** with Google identity, console shows `idProvider: github`
5. Logout of **site 1**
6. Login to **site 1** with GitHub identity (which should fail), and be greeted with `idProvider: github` and a tilted lock.

Because both providers are registered in the farm, it will not reject the Passport client that had not been persisted as chosen provider to `owner.json`. I know farm mode was always only considered a hack, but I'm depending largely on it, and am almost sorry to cause this trouble.

**Comment by paul90** [comment]
This is very strange, as I'm not seeing it misbehaving like that.

Can you check that your wiki has wiki-security-passportjs: 0.9.0 - running `wiki -v` or `node index.js -v` will list the versions of all the wiki components.
Can you also check that the `owner.json`, in the status directory, have the expect values. There should just be the one entry there.

**Comment by almereyda** [comment]
Thank you for reminding me to check again, if the build I am using was correct. In fact, it wasn't, and there was an error in the build manifests that led to a wrong source ref during checkout of the build context. This discovery was unexpected, please pardon me the distraction.

Glad we got some more log output to showcase the previous error, which is gone now.
