### ISSUE TITLE
Changes required in Twitter config?

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-security-passportjs#5]
I've created a new Twitter "app" and configured it with the callback url blank as suggested here:

![screen shot 2016-11-20 at 4 33 30 pm](https://cloud.githubusercontent.com/assets/12127/20467598/9fccf882-af3f-11e6-8526-b8e24c4aa880.png)

When I tried to login with Twitter I got the "‘oob’/oauth/request_token" error described here:

https://twittercommunity.com/t/desktop-applications-only-support-the-oauth-callback-value-oob-oauth-request-token/252

The support page suggested putting a placeholder in the field. I put "http://bay.fed.wiki" in the field, updated the config, restarted the wiki server, and then login worked fine.

**Comment by paul90** [comment]
updated documentation published as part of + wiki-security-passportjs@0.1.1
