### ISSUE TITLE
Is passportjs part of current wiki install?

### ISSUE THREAD

**Issue by andysylvester** [fedwiki/wiki-security-passportjs#9]
I have created a new wiki at http://fedwiki.andysylvester.com, have created a Twitter app, and have created a config.json file at /.wiki/config.json. I used the following command to start the wiki:

wiki -p 80 --config ~/.wiki/config.json

The wiki started, I went to the URL, it starts up, but I see the starting page with the "yellow border", and I do not see any way to "claim" the site, and I do not see any prompts.

Is this plugin part of the standard wiki install? Do I need to install something else from this repo?

**Comment by paul90** [comment]
The yellow border just means that the current view of that page is saved in your browser, if you click on 'Recent Changes' then 'Local Changes' you will get a page which shows which wiki pages are saved in the browser. If they are a version you want to keep, you can click on 'export changes' and save the export page for importing later. You can also remove the version of the page saved in the browser by clicking on `x` by the page name.

Yes, this plugin is part of the standard wiki install - you should see a yellow padlock in the bar at the bottom of the browser window. Clicking on this will open a login window, which as you have Twitter configured will allow you to login with twitter. As the wiki is unclaimed will also claim it for you. If you visit other wiki within the farm while logged in there will be a _key_ by the padlock that you can use to claim those other wiki sites.

**Comment by andysylvester** [comment]
Paul, thanks for the advice. I was able to "claim" my wiki with the Twitter app login using your instructions. On the "yellow border" problem, I was able to fork the page (per info on this page: https://hapgood.us/2014/09/01/using-federated-wiki-in-the-classroom-getting-started/) and save it. I don't know what to click on to "export changes", would appreciate an explanation of that step.

**Comment by paul90** [comment]
The 'Local Changes' page contains two sections:

1. a list of the pages that have been saved to browser local storage. Each line has the page title, which is a link to the page, and a button to delete the version stored in browser local storage.
1. a button that allows you to export an archive of the pages stored in browser local storage. The gives you a page of JSON that you can save, really should give a file you can save. This can be used in the same way as the export, '/system/export.json'.

The main use of the local changes export is where a page has edited on somebody else's wiki. Allowing you to get a copy that you can import into your own wiki. But, it is also useful if you edit a page while not logged in, and want to see the original version before overwriting it with a fork from local storage.

**Comment by andysylvester** [comment]
Paul, thank you for that explanation!

My video of using the Twitter option for Passport authentication is now available at https://www.youtube.com/watch?v=VVuHGCkSHlg&feature=youtu.be.

**Comment by WardCunningham** [comment]
Very nice videos. I especially like the focus and pace.

**Comment by andysylvester** [comment]
Thanks!

I have fleshed out my first take on how I set up my new wiki, it is available at http://fedwiki.andysylvester.com/view/welcome-visitors/view/journal-2017/view/new-user-setup. I would like to get some feedback on this and review by others, do you have any suggestions where I should post this request?

**Comment by paul90** [comment]
The is a fairly old page on setting up wiki on Ubuntu 14.x, see http://goals.pod.rodwell.me/federated-wiki-on-digital-ocean.html - a good proportion of that page is automating keeping the platform up to date, not sure what has changed with Ubuntu 16.x. An obvious difference is that upstart is not the default, so new systemd init scripts will be needed.

**Comment by andysylvester** [comment]
Paul, thanks for the reference to this wiki setup page. The part of the puzzle that I still want to figure out is how to start wiki automatically if the server undergoes a restart. As you mentioned, my understanding is that upstart is not the standard tool on Ubuntu 16.X.

I would like to see a more centralized area to collect wiki setup information, and to help be a portal to the federated wiki world. Some examples that I think look good are:
* https://github.com/d3/d3/wiki
* https://d3js.org/
* https://www.djangoproject.com/

I plan to keep working on this concept. Again, feedback is welcome, I am planning to open an issue on the main wiki repo once I have something ready for review.

**Comment by WardCunningham** [comment]
I have started on "Tips for Administrators" that heads in this direction.

http://admin.asia.wiki.org/view/welcome-visitors/view/tips-for-administrators/view/hosting/view/laptops

**Comment by andysylvester** [comment]
Ward, thanks for the pointer. What would be the best way for me to collaborate on this subject?

**Comment by WardCunningham** [comment]
If you make a parallel site, say `admin.fedwiki.andysylvester.com`, then you could fork my `hosting` page into your admin site and start writting.

When I fork you copy of `hosting` back into my site then we will have joined the two admin wikis into one from both directions. Wiki will discover this joint automatically for anyone interested in hosting no matter where they start.

Of course you don't need me to do anything for a one-way connection. When you fork my page then your readers get the rest of my admin site with an automatic preference for your copy of any pages we duplicate.

(I could write a little more here about forking if you'd like.)

**Comment by WardCunningham** [comment]
Here is a video that shows joining sites the was I have just described.

http://video.fed.wiki.org/view/welcome-visitors/view/federated-wiki-videos/view/23-page-drag-link

**Comment by andysylvester** [comment]
Ward, how I can I create a parallel site like admin.fedwiki.andysylvester.com? I am running a farm, and I have pointed admin.fedwiki.andysylvester.com to the IP address for the server running fedwiki.andysylvester.com (waiting for DNS to propagate). I did go ahead and fork the Tips for Adminstrators page to http://fedwiki.andysylvester.com/view/welcome-visitors/view/journal-2017/view/tips-for-administrators.

**Comment by andysylvester** [comment]
Ooops - I spoke too soon! Looks like the DNS propagation finished and the admin site created itself!

http://admin.fedwiki.andysylvester.com/view/welcome-visitors/view/tips-for-administrators

**Comment by WardCunningham** [comment]
I forked that page. Now that we've passed that page back and forth we've made the two way connection. I'll close this issue since we have drifted some distance from the original question.

**Comment by paul90** [comment]
Of course the other way of joining a group of wiki together is to use a common roster.
